services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    ports:
      - "5432:5432"

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    ports:
      - "6379:6379"

  elasticmq:
    extends:
      file: docker-compose.base.yml
      service: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"

  # Use the data connector to manage the database
  # https://github.com/inferablehq/inferable/tree/main/data-connector
  # data-connector:
  #   image: inferable/data-connector:latest
  #   environment:
  #     INFERABLE_API_SECRET: ${INFERABLE_API_SECRET}
  #   depends_on:
  #     - postgres
  #   configs:
  #     - source: connector_config
  #       target: /app/config.json

volumes:
  pgdata:
  elasticmqdata:

configs:
  elasticmq_conf:
    content: |
      include classpath("application.conf")

      queues {
        run-process {}
        run-generate-name {}
        email-ingestion {}
        customer-telemetry {}
        external-tool-call {}
      }

  # connector_config:
  #   content: |
  #     {
  #       "privacyMode": 0,
  #       "approvalMode": 0,
  #       "connectors": [
  #         {
  #           "type": "postgres",
  #           "name": "developmentPostgres",
  #           "connectionString": "postgresql://inferable:inferable@postgres:5432/inferable",
  #           "schema": "public"
  #         }
  #       ]
  #     }
