name: Create Archives of Bootstrap Projects

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      bootstrap: ${{ steps.filter.outputs.bootstrap }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Filter changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            bootstrap:
              - 'bootstrap*/**'

  create-archives:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.bootstrap == 'true' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive bootstrap-node
        run: |
          zip -r "archives/bootstrap-node.zip" "bootstrap-node/"

      - name: Archive bootstrap-dotnet
        run: |
          zip -r "archives/bootstrap-dotnet.zip" "bootstrap-dotnet/"

      - name: Archive bootstrap-go
        run: |
          zip -r "archives/bootstrap-go.zip" "bootstrap-go/"

      - name: Commit archives
        uses: EndBug/add-and-commit@v9
        with:
          add: 'archives/'
          message: '[skip ci] Update bootstrap project archives'
          default_author: github_actions
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}


